### ISSUE TITLE
What about translating using Transifex?

### ISSUE THREAD

**Issue by yarons** [ZeeRooo/Translations#14]
Can we use this project to work on the translations?

https://www.transifex.com/yaron/materialfbook/dashboard/

**Comment by ZeeRooo** [comment]
Sure, no problem.

2017-03-28 10:14 GMT-03:00 Yaron Shahrabani <notifications@github.com>:

**Comment by ZeeRooo** [comment]
@yarons Can you update and add all the languages in Transifex according to this repo? Then we will be able to use Transifex instead my repo.

**Comment by yarons** [comment]
Updated, apparently the non translated strings are in English and they seem translated but the work is saved in the system.
